#!/bin/bash

#Parameters
PRODUCT_HOME=/Applications/__PRODUCT__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 777 .
cd hardwario-code
xattr -dr com.apple.quarantine Visual\ Studio\ Code.app
echo "Post installation process finished"