#!/bin/bash

#Parameters
PRODUCT_HOME=/tmp/

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
cd hardwario-code
chmod -R 777 .
xattr -dr com.apple.quarantine Visual\ Studio\ Code.app

mkdir -p ~/Applications/
mv /tmp/hardwario-code -f ~/Applications/
rm -rf /tmp/hardwario-code

mv ~/Applications/hardwario-code/Visual\ Studio\ Code.app ~/Applications/hardwario-code/HARDWARIO\ Code.app
xattr -dr com.apple.quarantine ~/Applications/hardwario-code/HARDWARIO\ Code.app

mv ~/Applications/hardwario-code ~/Applications/HARDWARIO\ Code

echo "Post installation process finished"